---
abstract: 'provides Log::Any support for OpenTracing spans'
author:
  - 'Tom Molesworth <TEAM@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Log::Any: '0'
  Log::Any::Adapter: '0'
  OpenTracing::DSL: '0'
  Test::CheckDeps: '0.010'
  Test::More: '0.94'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.015, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Log-Any-Adapter-OpenTracing
no_index:
  directory:
    - eg
    - share
    - shares
    - t
    - xt
provides:
  Log::Any::Adapter::OpenTracing:
    file: lib/Log/Any/Adapter/OpenTracing.pm
    version: '0.001'
requires:
  Carp: '0'
  Log::Any::Adapter::Base: '1.500'
  Log::Any::Adapter::Util: '0'
  OpenTracing: '1.001'
  OpenTracing::Any: '0'
  indirect: '0'
  parent: '0'
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/team-at-cpan/Log-Any-Adapter-OpenTracing/issues
  homepage: https://github.com/team-at-cpan/Log-Any-Adapter-OpenTracing
  repository: https://github.com/team-at-cpan/Log-Any-Adapter-OpenTracing.git
version: '0.001'
x_authority: cpan:TEAM
x_generated_by_perl: v5.30.2
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
